{ pkgs, lib, config, ... }:

let
  overridesCfg = ''
    // Generated by Home Manager.
    defaultPref("browser.compactmode.show", true);
    defaultPref("browser.startup.page", 3);
    defaultPref("browser.tabs.drawInTitlebar", true);
    defaultPref("browser.theme.content-theme", 0);
    defaultPref("browser.theme.toolbar-theme", 0);
    defaultPref("browser.uidensity", 1);
    defaultPref("layout.css.prefers-color-scheme.content-override", 0);
    defaultPref("privacy.fingerprintingProtection", true);
    defaultPref("privacy.fingerprintingProtection.overrides", "+AllTargets,-CSSPrefersColorScheme");
    defaultPref("privacy.resistFingerprinting", false);
    defaultPref("ui.systemUsesDarkTheme", 1);
    defaultPref("font.size.variable.x-western", 16);
    defaultPref("font.size.monospace.x-western", 14);
    defaultPref("font.minimum-size.x-western", 14);
    defaultPref("widget.dmabuf.force-enabled", true);
    defaultPref("widget.wayland", true);

    pref("privacy.resistFingerprinting", false);
    pref("privacy.fingerprintingProtection", true);
    pref("privacy.fingerprintingProtection.overrides", "+AllTargets,-CSSPrefersColorScheme");
    pref("layout.css.prefers-color-scheme.content-override", 0);
    pref("privacy.sanitize.sanitizeOnShutdown", false);
    pref("privacy.clearOnShutdown.cookies", false);
    pref("privacy.clearOnShutdown.cache", false);
    pref("font.size.variable.x-western", 16);
    pref("font.size.monospace.x-western", 14);
    pref("font.minimum-size.x-western", 14);
    pref("network.cookie.lifetimePolicy", 0);
  '';
in
{
  programs.librewolf = {
    enable = true;
    package = pkgs.librewolf;
    nativeMessagingHosts = [ ];
    pkcs11Modules = [ ];
    enableGnomeExtensions = false;
    languagePacks = [ ];
    profiles.jake = {
      id = 0;
      name = "jake";
      path = "jake";
      isDefault = true;
      settings = { };
      extraConfig = "";
      userChrome = "";
      userContent = "";
      search.default = "Google";
    };
  };

  home.activation.forceDarkMode = lib.hm.dag.entryAfter ["writeBoundary"] ''
    find "${config.home.homeDirectory}/.librewolf" -name "*.hm-backup" -delete
    cat > "${config.home.homeDirectory}/.librewolf/librewolf.overrides.cfg" << 'EOF'
    ${overridesCfg}
    EOF
  '';
}
